version: "3"
services:
  redis:
    image: redis
    ports:
      - "6001:6379"
  serverless-redis-http:
    ports:
      - "6002:80"
    image: hiett/serverless-redis-http:latest
    environment:
      SRH_MODE: env
      SRH_TOKEN: token_for_development_use_only
      SRH_CONNECTION_STRING: "redis://redis:6379" # Using `redis` hostname since they're in the same Docker network.
