version: "3"
services:
  redis:
    image: redis
    ports:
      - "26001:6379"
  serverless-redis-http:
    ports:
      - "26002:80"
    image: hiett/serverless-redis-http:latest
    environment:
      SRH_MODE: env
      SRH_TOKEN: example_token
      SRH_CONNECTION_STRING: "redis://redis:6379" # Using `redis` hostname since they're in the same Docker network.
